[phases.setup]
  nixPkgs = ['python310', 'python310Packages.pip', 'ffmpeg']

[phases.install]
  cmds = ['pip install -r requirements.txt']

[phases.build]
  cmds = []

[start]
  cmd = 'python bot.py'
