[phases.setup]
  nixPkgs = ['python310', 'python310Packages.pip', 'ffmpeg']

[phases.install]
  cmds = [
    'python -m venv /app/venv',
    '. /app/venv/bin/activate',
    'pip install -r requirements.txt'
  ]

[phases.build]
  cmds = []

[start]
  cmd = '/app/venv/bin/python bot.py'
